version: "3"

services:
  # Application service layer
  php:
    build:
      context: 
        ./php
    volumes:
      - "./app:/var/www/html"
    ports:
      - "9000:9000"

  # Web service layer
  nginx:
    image: nginx:1.14
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - php