source :rubygems
gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pg'
gem 'rake'
gem 'pg_search', '~> 2.0.1'

# Makes http fun! Also, makes consuming restful web services dead easy.
gem 'httparty', '~> 0.16.4'

group :development do
  gem 'tux'
end