version: '3'

services:
  rails:
    image: andbrandao/ubuntu-ssh
    volumes:
      - .:/projects
    ports:
      - "3000"
      - "22"
  db:
    images: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432"