# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ab5bb92bee622aaaaaf61471933da37e0d81c66dd9366f537b18170198f6dd3421e4e992dd4a59318eb771023b589c901eb905d66cad94b30946e0a5292f429

test:
  secret_key_base: 46d5b8d755356630d2873438cbfe9c09a4f94dcece6c7a03dc737574de5243be8a75afa69251b0776b025bfb2b0cc87eddceb9c35b0e96f9b477b5acdadc623a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
