source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Unicorn as the app server
# gem 'unicorn'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
  
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'faker', '~> 1.9', '>= 1.9.1'
end

#A set of common locale data and translations to internationalize and/or localize your Rails applications.
gem 'rails-i18n', '~> 4.0'

#pt-BR text generator
gem 'lerolero_generator'

#Avoid repeating yourself, use pry-rails instead of copying the initializer to every rails project. This is a small gem which causes rails console to open pry. It therefore depends on pry.
gem 'pry-rails', :group => :development

#Dynamic nested forms using jQuery made easy
gem "cocoon"

#A Scope & Engine based, clean, powerful, customizable and sophisticated paginator for Ruby webapps
gem 'kaminari'

# I18n for kaminari
gem 'kaminari-i18n'

# Gem for installing nodejs
gem 'nodejs-rails', '~> 0.0.1'

# Use NPM packages in you Ruby on Rails application
gem 'npm-rails', '~> 0.2.1'

# Manage your Ruby application's gem dependencies
gem 'bundler', '>= 1.8.4'

# A simple, versatile notification library
gem 'rails-assets-notifyjs', source: 'https://rails-assets.org'

# A front-end javascript framework
gem 'rails-assets-bootstrap', source: 'https://rails-assets.org'

# font-awesome-rails provides the Font-Awesome web fonts and stylesheets as a Rails engine for use with the asset pipeline
gem "font-awesome-rails"

group :production do
  #Heroku dependencies
  gem 'pg'
  gem 'rails_12factor'  
end
